In [1]:
import numpy as np

### < 3.2.2 > : 계단 함수

In [2]:
# Simple step function
def step_function_(x):
  if x > 0:
    return 1
  elif x <= 0:
    return 0

In [3]:
# More general step function
def step_function(x):
  flag = x > 0
  res = flag.astype(int) # np.int32 or np.int64
  return res

In [4]:
# Function's process debugging
x = np.array([-1.0, 1.0, 2.0])
x

array([-1.,  1.,  2.])

In [5]:
flag = x > 0
flag

array([False,  True,  True])

In [6]:
res = flag.astype(int)
res

array([0, 1, 1])

---

### < 3.2.4 > : 시그모이드 함수

In [7]:
# Sigmoid function
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [8]:
# Test samples (e.g. numpy)
x = np.array([-1.0, 1.0, 2.0])
sigmoid(x)

array([0.26894142, 0.73105858, 0.88079708])

In [9]:
# How can this possible? : Broadcasting
t = np.array([1.0, 2.0, 3.0])

In [10]:
1.0 + t

array([2., 3., 4.])

In [11]:
1.0 / t

array([1.        , 0.5       , 0.33333333])

---

### < 3.2.7 > : ReLU 함수

In [12]:
# ReLU function
def relu(x):
  return np.maximum(x, 0)

---

### < 3.3.1 > : 다차원 배열

In [13]:
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [14]:
np.ndim(A)

1

In [15]:
A.shape

(4,)

In [16]:
A.shape[0]

4

In [17]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
np.ndim(B)

2

In [19]:
B.shape

(3, 2)

---

### < 3.3.2 > : 행렬의 곱

In [20]:
A = np.array([[1, 2], [3, 4]])
A.shape

(2, 2)

In [21]:
B = np.array([[5, 6], [7, 8]])
B.shape

(2, 2)

In [22]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [23]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [24]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B.shape

(3, 2)

In [25]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [26]:
C = np.array([[1, 2], [3, 4]])
C.shape

(2, 2)

In [27]:
A.shape

(2, 3)

In [28]:
np.dot(A, C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [29]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A.shape

(3, 2)

In [30]:
B = np.array([7, 8])
B.shape

(2,)

In [31]:
np.dot(A, B)

array([23, 53, 83])

---

### < 3.3.3 > : 신경망에서의 행렬 곱

In [32]:
X = np.array([1, 2])
X.shape

(2,)

In [33]:
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [34]:
W.shape

(2, 3)

In [35]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]


---

### < 3.4.2 > : 각 층의 신호 전달

In [36]:
# Input -> 1st hidden layer
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(X.shape)
print(W1.shape)
print(B1.shape)

(2,)
(2, 3)
(3,)


In [37]:
A1 = np.dot(X, W1) + B1
Z1 = sigmoid(A1)

print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [38]:
# 1st hidden layer -> 2nd hidden layer
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [39]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

print(A2)
print(Z2)

[0.51615984 1.21402696]
[0.62624937 0.7710107 ]


In [40]:
# 2nd hidden layer -> output layer
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

print(Z2.shape)
print(W3.shape)
print(B3.shape)

(2,)
(2, 2)
(2,)


In [41]:
A3 = np.dot(Z2, W3) + B3

print(A3)

[0.31682708 0.69627909]


In [42]:
def identity_function(x):
  return x

Y = identity_function(A3)
print(Y)

[0.31682708 0.69627909]


---

### < 3.5.1 > : 소프트맥스 함수

In [43]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [44]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [45]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [46]:
# Define softmax activation function
def softmax_(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a
  return y

---

### < 3.5.2 > : 소프트맥스 함수 구현 시 문제점

In [47]:
import warnings
warnings.filterwarnings(action="ignore")

In [48]:
# Overflow Problem
a = np.array([1010, 1000, 990])
softmax_(a)

array([nan, nan, nan])

In [49]:
c = np.max(a)
a - c

array([  0, -10, -20])

In [50]:
softmax_(a - c)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [51]:
# Improved version
def softmax(a):
  c = np.max(a)
  exp_a = np.exp(a - c) # Solution
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a
  return y

---

### < 3.5.3 > : 소프트맥스 함수의 특징

In [52]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [53]:
np.sum(y)

np.float64(1.0)

---