In [1]:
import numpy as np

### < 1.5.2 > : 배열 생성

In [2]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [3]:
type(x)

numpy.ndarray

### < 1.5.3 > : 산술 연산

In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [5]:
x - y

array([-1., -2., -3.])

In [6]:
x * y

array([ 2.,  8., 18.])

In [7]:
x / y

array([0.5, 0.5, 0.5])

In [8]:
x / 2.0

array([0.5, 1. , 1.5])

### < 1.5.4 > : N차원 배열

In [9]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [10]:
A.shape

(2, 2)

In [11]:
A.dtype

dtype('int64')

In [12]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [13]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [14]:
A * 10

array([[10, 20],
       [30, 40]])

### < 1.5.5 > : 브로드캐스트

In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

### < 1.5.6 > : 원소 접근

In [16]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [17]:
X[0]

array([51, 55])

In [18]:
X[0][1]

np.int64(55)

In [19]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [20]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [21]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [22]:
X > 15

array([ True,  True, False,  True, False, False])

In [23]:
X[X > 15]

array([51, 55, 19])